version: '2'
services:
    cryptotradingbot-app:
        image: cryptotradingbot
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://cryptotradingbot-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=cryptoTradingBot
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cryptotradingbot-mongodb:
        extends:
            file: mongodb.yml
            service: cryptotradingbot-mongodb
